extends Node
## Global signal bus. Append-only: add new signals at the end, never rename existing ones.

# --- world ---
signal world_loaded(world: Node)
signal world_unloading(world: Node)
signal block_changed(pos: Vector3i, old_id: int, new_id: int)
signal chunk_ready(cx: int, cz: int)
signal time_changed(time_ticks: float)
signal weather_changed(kind: String)
signal planet_changed(planet_id: String)
signal explosion(center: Vector3, radius: float, power: float)
signal splash(pos: Vector3, strength: float)

# --- player ---
signal player_spawned(player: Node)
signal player_damaged(amount: float, source: Node, kind: String)
signal player_died(killer: Node)
signal player_respawned()
signal health_changed(current: float, maximum: float)
signal ki_changed(current: float, maximum: float)
signal stamina_changed(current: float, maximum: float)
signal hunger_changed(current: float, maximum: float)
signal oxygen_changed(current: float, maximum: float)
signal stats_changed()
signal tp_changed(tp: int, total: int)
signal level_up(new_level: int)
signal skill_changed(skill_id: String, level: int)
signal technique_learned(technique_id: String)
signal item_picked_up(item_id: String, count: int)
signal inventory_changed()
signal hotbar_changed(index: int)
signal target_changed(target: Node)
signal camera_mode_changed(mode: int)

# --- entities / combat ---
signal entity_spawned(entity: Node)
signal entity_died(entity: Node, killer: Node)
signal entity_damaged(entity: Node, amount: float, source: Node, kind: String, crit: bool)
signal form_changed(entity: Node, form_id: String)
signal transformation_started(entity: Node, form_id: String)
signal transformation_finished(entity: Node, form_id: String)
signal technique_started(entity: Node, technique_id: String)
signal technique_fired(entity: Node, technique_id: String)
signal ki_charge_changed(entity: Node, charging: bool)
signal boss_engaged(entity: Node)
signal boss_defeated(entity: Node)

# --- quests / story ---
signal quest_started(quest_id: String)
signal quest_objective_progress(quest_id: String, objective_index: int, current: int, required: int)
signal quest_completed(quest_id: String)
signal quest_failed(quest_id: String)
signal quest_reward_claimed(quest_id: String)
signal quest_tracked(quest_id: String)
signal saga_completed(saga_id: String)
signal dialog_requested(npc: Node)
signal dialog_closed(npc: Node)
signal dragon_ball_found(set_id: String, star: int)
signal dragon_summoned(dragon_id: String)
signal wish_granted(dragon_id: String, wish_id: String)
signal planet_unlocked(planet_id: String)
signal travel_requested(planet_id: String)

# --- ui / feedback ---
signal ui_opened(screen: String)
signal ui_closed(screen: String)
signal toast(title: String, text: String, icon: Texture2D)
signal hint(text: String, seconds: float)
signal screen_shake(strength: float, duration: float)
signal screen_flash(color: Color, duration: float)
signal damage_number(pos: Vector3, amount: float, crit: bool, color: Color)
signal saving_started()
signal saving_finished()
signal settings_changed()
