package com.cubicworld.audio

import com.badlogic.gdx.Gdx
import com.badlogic.gdx.audio.Music
import com.badlogic.gdx.audio.Sound

/**
 * Owns all game audio: one-shot sound effects, looping ambience beds and the
 * four crossfading music loops generated by tools/gen_sounds.py.
 *
 * Sound effects are loaded as [Sound]; music and ambience as looping [Music].
 * Missing files only produce a log warning - every playback path is
 * null-guarded so the game runs fine with partial (or no) audio assets.
 */
class AudioManager {

    var musicVolume: Float = 0.7f
        set(value) { field = value.coerceIn(0f, 1f) }
    var soundVolume: Float = 1.0f
        set(value) { field = value.coerceIn(0f, 1f) }
    var ambienceVolume: Float = 0.8f
        set(value) { field = value.coerceIn(0f, 1f) }

    private val sounds = HashMap<String, Sound>()
    private val musicTracks = HashMap<String, Music>()     // day/night/underground/danger
    private val ambienceTracks = HashMap<String, Music>()  // wind/rain/cave

    /** Current fade level (0..1) per track key; multiplied by the master volume. */
    private val musicLevels = HashMap<String, Float>()
    private val ambienceLevels = HashMap<String, Float>()

    private var musicTarget: String? = null
    private var ambienceTarget: String? = null
    private var paused = false
    private var loaded = false

    /** Loads every known sound effect, music loop and ambience loop. */
    fun load() {
        if (loaded) return
        loaded = true
        for (name in SOUND_NAMES) {
            val file = Gdx.files.internal("$AUDIO_DIR/$name.wav")
            if (!file.exists()) {
                warn("sound missing: $name.wav")
                continue
            }
            try {
                sounds[name] = Gdx.audio.newSound(file)
            } catch (e: Exception) {
                warn("failed to load sound $name.wav: ${e.message}")
            }
        }
        for (key in MUSIC_KEYS) loadTrack(musicTracks, key, "music_$key")
        for (key in AMBIENCE_KEYS) loadTrack(ambienceTracks, key, "ambience_$key")
    }

    private fun loadTrack(into: MutableMap<String, Music>, key: String, baseName: String) {
        val file = Gdx.files.internal("$AUDIO_DIR/$baseName.wav")
        if (!file.exists()) {
            warn("track missing: $baseName.wav")
            return
        }
        try {
            val music = Gdx.audio.newMusic(file)
            music.isLooping = true
            music.volume = 0f
            into[key] = music
        } catch (e: Exception) {
            warn("failed to load track $baseName.wav: ${e.message}")
        }
    }

    /** Plays a one-shot effect by base name, e.g. "break_stone". Unknown names are a no-op. */
    fun play(name: String, volume: Float = 1f) {
        val sound = sounds[name] ?: return
        val v = (volume * soundVolume).coerceIn(0f, 1f)
        if (v <= 0f) return
        try {
            sound.play(v)
        } catch (e: Exception) {
            warn("failed to play $name: ${e.message}")
        }
    }

    /**
     * Selects the music loop for the current situation
     * (priority: danger > underground > night > day) and crossfades to it.
     * Fades themselves advance in [update].
     */
    fun updateMusic(delta: Float, night: Boolean, underground: Boolean, danger: Boolean) {
        musicTarget = when {
            danger -> "danger"
            underground -> "underground"
            night -> "night"
            else -> "day"
        }
    }

    /** Crossfades ambience to "wind", "rain", "cave", or fades all out for null. */
    fun setAmbience(kind: String?) {
        ambienceTarget = if (kind != null && kind in AMBIENCE_KEYS) {
            kind
        } else {
            if (kind != null) warn("unknown ambience: $kind")
            null
        }
    }

    /** Advances all crossfades. Call once per frame. */
    fun update(delta: Float) {
        if (paused) return
        advance(musicTracks, musicLevels, musicTarget, musicVolume, delta)
        advance(ambienceTracks, ambienceLevels, ambienceTarget, ambienceVolume, delta)
    }

    private fun advance(
        tracks: Map<String, Music>,
        levels: MutableMap<String, Float>,
        target: String?,
        master: Float,
        delta: Float
    ) {
        val step = delta / FADE_SECONDS
        for ((key, music) in tracks) {
            val goal = if (key == target) 1f else 0f
            var level = levels[key] ?: 0f
            level = when {
                level < goal -> (level + step).coerceAtMost(goal)
                level > goal -> (level - step).coerceAtLeast(goal)
                else -> level
            }
            levels[key] = level
            try {
                if (level > 0f) {
                    music.volume = (level * master).coerceIn(0f, 1f)
                    if (!music.isPlaying) music.play()
                } else if (music.isPlaying) {
                    music.pause()
                }
            } catch (e: Exception) {
                warn("music update failed for $key: ${e.message}")
            }
        }
    }

    /** Stops music and ambience (app pause). Sound effects are fire-and-forget. */
    fun pauseAll() {
        paused = true
        forEachTrack { it.pause() }
    }

    fun resumeAll() {
        paused = false
        // Tracks with a non-zero fade level come straight back; the rest
        // resume naturally through update() as their fades rise.
        for ((key, music) in musicTracks) {
            if ((musicLevels[key] ?: 0f) > 0f) safePlay(music)
        }
        for ((key, music) in ambienceTracks) {
            if ((ambienceLevels[key] ?: 0f) > 0f) safePlay(music)
        }
    }

    fun dispose() {
        for (sound in sounds.values) runCatching { sound.dispose() }
        for (music in musicTracks.values) runCatching { music.dispose() }
        for (music in ambienceTracks.values) runCatching { music.dispose() }
        sounds.clear()
        musicTracks.clear()
        ambienceTracks.clear()
        musicLevels.clear()
        ambienceLevels.clear()
        loaded = false
    }

    private inline fun forEachTrack(action: (Music) -> Unit) {
        for (music in musicTracks.values) runCatching { action(music) }
        for (music in ambienceTracks.values) runCatching { action(music) }
    }

    private fun safePlay(music: Music) {
        try {
            if (!music.isPlaying) music.play()
        } catch (e: Exception) {
            warn("failed to resume track: ${e.message}")
        }
    }

    private fun warn(message: String) {
        Gdx.app?.log("AudioManager", message)
    }

    companion object {
        private const val AUDIO_DIR = "audio"
        private const val FADE_SECONDS = 2f

        private val MUSIC_KEYS = listOf("day", "night", "underground", "danger")
        private val AMBIENCE_KEYS = listOf("wind", "rain", "cave")

        private val SOUND_NAMES: List<String> = buildList {
            val materials = listOf(
                "earth", "stone", "wood", "plant", "metal", "glass", "cloth", "liquid"
            )
            for (m in materials) add("break_$m")
            for (m in materials) add("place_$m")
            addAll(
                listOf(
                    "dig_earth", "step_grass", "step_stone", "step_wood", "step_sand",
                    "tool_break", "hit", "hurt", "creature_die", "eat", "click",
                    "splash", "chirp", "pop"
                )
            )
        }
    }
}
