package com.cubicworld.render

import com.badlogic.gdx.Gdx
import com.badlogic.gdx.graphics.Texture
import com.badlogic.gdx.utils.JsonReader

/**
 * The single block/item/creature texture atlas, generated by tools/gen_textures.py.
 * atlas.json maps tile names to grid indices; UVs get a half-texel inset so
 * nearest-filtered tiles never bleed into their neighbours.
 */
class TextureAtlasManager {

    lateinit var texture: Texture
        private set
    private val indexByName = HashMap<String, Int>()
    private var cols = 16
    private var rows = 8
    private var tileSize = 16

    fun load() {
        val json = JsonReader().parse(Gdx.files.internal("textures/atlas.json"))
        cols = json.getInt("cols")
        rows = json.getInt("rows")
        tileSize = json.getInt("tileSize")
        val tiles = json.get("tiles")
        var t = tiles.child
        while (t != null) {
            indexByName[t.name] = t.asInt()
            t = t.next
        }
        texture = Texture(Gdx.files.internal("textures/atlas.png"), false).apply {
            setFilter(Texture.TextureFilter.Nearest, Texture.TextureFilter.Nearest)
        }
    }

    fun tileIndex(name: String): Int =
        indexByName[name] ?: throw IllegalStateException("Missing texture tile '$name'")

    fun hasTile(name: String): Boolean = name in indexByName

    /** [u0, v0, u1, v1] with a half-texel inset. */
    fun uv(index: Int, out: FloatArray) {
        val col = index % cols
        val row = index / cols
        val texW = (cols * tileSize).toFloat()
        val texH = (rows * tileSize).toFloat()
        val inset = 0.5f
        out[0] = (col * tileSize + inset) / texW
        out[1] = (row * tileSize + inset) / texH
        out[2] = ((col + 1) * tileSize - inset) / texW
        out[3] = ((row + 1) * tileSize - inset) / texH
    }

    fun dispose() {
        if (this::texture.isInitialized) texture.dispose()
    }
}
