// Generates the data-heavy documents straight from the source data so they
// can never drift from what the packs actually contain:
//   docs/02_FLOOR_PLAN.md          coordinate registry, rooms, cameras, route graph, inputs
//   docs/05_NIGHTS_AND_BALANCE.md  night table, formulas, power maths, simulation results
// Run: node tools/gen_docs.mjs   (re-runs the balance simulation, ~15 s)
import fs from 'node:fs';
import path from 'node:path';
import { ORIGIN, LEVELS, ROOMS, STAIRS, OPENINGS, TICKING_AREAS, ANCHORS, PROPERTY, OFFICE_BOUNDS } from '../packs/FredbearBP/scripts/data/layout.js';
import { NODES, EDGES, ACCESS, ENTRY_NODE, ENTRY_BARRIER, GOLDEN_NODES, edgePolyline, polylineLength } from '../packs/FredbearBP/scripts/data/nodes.js';
import { CAMERAS } from '../packs/FredbearBP/scripts/data/cameras.js';
import { INPUTS, inputCbPos } from '../packs/FredbearBP/scripts/data/inputs.js';
import { CONTROL, MODULES } from '../packs/FredbearBP/scripts/data/actuators.js';
import { CONFIG } from '../packs/FredbearBP/scripts/core/config.js';
import { simulate, table, detailTable } from './balance_sim.mjs';

const ROOT = new URL('../', import.meta.url).pathname;
const w = (x, y, z) => `${x + ORIGIN.x} ${y + ORIGIN.y} ${z + ORIGIN.z}`;
const fmt = (v) => (Number.isInteger(v) ? String(v) : v.toFixed(1));
const GEN = '<!-- GENERATED by tools/gen_docs.mjs from the pack data. Do not edit by hand. -->';

// ============================================================ 02 floor plan
function floorPlan() {
  const L = [];
  L.push('# 02 · Floor plan and coordinate registry', '', GEN, '');
  L.push('## Coordinate system', '');
  L.push(`All map data is authored in **local coordinates**. World = local + ORIGIN, with ORIGIN = (${ORIGIN.x}, ${ORIGIN.y}, ${ORIGIN.z}).`);
  L.push('X runs west→east, Z runs north→south (Minecraft convention), Y is up.');
  L.push(`The property spans local x ${PROPERTY.x1}..${PROPERTY.x2}, z ${PROPERTY.z1}..${PROPERTY.z2} (a ${PROPERTY.x2 - PROPERTY.x1 + 1} × ${PROPERTY.z2 - PROPERTY.z1 + 1} footprint) on a plinth from local y ${PROPERTY.bottomY} to ${PROPERTY.topY} with a ${PROPERTY.berm}-block earth berm; outdoor grade is local y ${PROPERTY.gradeY}.`, '');
  L.push('| Level | Name | Floor block y (local) | Standing y (local) | Standing y (world) |', '|---|---|---|---|---|');
  for (const lv of Object.values(LEVELS)) L.push(`| ${lv.id} | ${lv.name} | ${lv.floorY} | ${lv.stand} | ${lv.stand + ORIGIN.y} |`);
  L.push('', '![Basement](floorplan_L0.png)', '![Ground floor](floorplan_L1.png)', '![Upper floor](floorplan_L2.png)', '');
  L.push('Legend for the rendered plans: walls `#`, props `p`, glass `g`, floors `.`, grass `,`, roofs `r`; coloured overlays show room labels, AI nodes, route edges, cameras and inputs (tools/render_floorplans.py).', '');
  L.push('## Ticking areas (chunk loading)', '');
  L.push('| Name | From (world) | To (world) |', '|---|---|---|');
  for (const t of TICKING_AREAS) L.push(`| ${t.name} | ${t.from.join(' ')} | ${t.to.join(' ')} |`);
  L.push('', 'Four ticking areas of 8 × 8 chunks keep the whole property, the basement and the command-block control room loaded at all times (created by the builder; `functions/fb/tickingareas.mcfunction` re-creates them).', '');
  L.push('## Anchors', '');
  L.push('| Anchor | Local x y z | World x y z | Yaw |', '|---|---|---|---|');
  for (const [k, a] of Object.entries(ANCHORS)) L.push(`| ${k} | ${fmt(a.x)} ${fmt(a.y)} ${fmt(a.z)} | ${fmt(a.x + ORIGIN.x)} ${fmt(a.y + ORIGIN.y)} ${fmt(a.z + ORIGIN.z)} | ${a.yaw ?? '-'} |`);
  L.push('', `Office interior bounds (local): x ${OFFICE_BOUNDS.x1}..${OFFICE_BOUNDS.x2}, z ${OFFICE_BOUNDS.z1}..${OFFICE_BOUNDS.z2}, y ${OFFICE_BOUNDS.y1}..${OFFICE_BOUNDS.y2}.`, '');
  L.push(`## Rooms (${ROOMS.length})`, '');
  L.push('Box = outer wall box `[x1, z1, x2, z2]` in local coordinates (walls included).', '');
  L.push('| ID | Name | Level | Box (local) | World NW corner | Zone | Purpose |', '|---|---|---|---|---|---|---|');
  for (const r of ROOMS) {
    const lv = LEVELS[r.level];
    L.push(`| ${r.id} | ${r.name} | ${r.level} | ${r.box.join(', ')} | ${w(r.box[0], lv.stand, r.box[1])} | ${r.zone ?? '-'} | ${(r.purpose ?? '').replace(/\|/g, '/')} |`);
  }
  L.push('', `Openings: ${OPENINGS.length} doors, archways and windows. Stairs, ladders and the office hatch:`, '');
  L.push('| ID | Kind | Local position | Direction | From → to standing y |', '|---|---|---|---|---|');
  for (const s of STAIRS) L.push(`| ${s.id} | ${s.kind} | ${s.x} ${s.z} | ${s.dir ?? '-'} | ${s.fromStand ?? '-'} → ${s.toStand ?? '-'} |`);
  L.push('', '## Security cameras (16)', '');
  L.push('| ID | Label | Room | Position (local) | Looks at (local) | Sees nodes | Notes |', '|---|---|---|---|---|---|---|');
  for (const c of CAMERAS) {
    const notes = [c.audioOnly ? 'audio only' : '', c.lostSignalBefore ? `no signal before night ${c.lostSignalBefore}` : ''].filter(Boolean).join('; ') || '-';
    L.push(`| ${c.id} | ${c.label} | ${c.room} | ${c.loc.map(fmt).join(' ')} | ${c.look.map(fmt).join(' ')} | ${c.sees.join(', ') || '-'} | ${notes} |`);
  }
  L.push('', '## AI route graph', '');
  L.push(`${NODES.length} nodes and ${EDGES.length} edges. Every edge is a polyline of waypoints the puppet follows; tools/validate_map.mjs samples every 0.5 blocks of every polyline against the voxel model (body + head cells must be passable), and the in-game self-test repeats the check against the built world.`);
  L.push(`Access letters: ${Object.entries(ACCESS).map(([k, v]) => `${v} = ${k}`).join(', ')}. Entries: ${Object.entries(ENTRY_NODE).map(([k, v]) => `${k} → ${v} (barrier ${ENTRY_BARRIER[k]})`).join(', ')}. Fredbear's golden nodes: ${GOLDEN_NODES.join(', ')}.`, '');
  const seenBy = {};
  for (const c of CAMERAS) for (const n of c.sees) (seenBy[n] ??= []).push(c.id);
  L.push('| Node | Room | Local x y z | Flags | Seen by |', '|---|---|---|---|---|');
  for (const n of NODES) {
    const flags = [n.home ? `home of ${n.home}` : '', n.golden ? 'golden' : '', n.dark ? 'dark' : '', n.entry ? `entry ${n.entry}` : '', n.kitchen ? 'kitchen' : '', n.crawl ? 'crawl' : '', n.zone ? `zone ${n.zone}` : ''].filter(Boolean).join(', ');
    L.push(`| ${n.id} | ${n.room} | ${fmt(n.x)} ${fmt(n.y)} ${fmt(n.z)} | ${flags} | ${(seenBy[n.id] ?? []).join(', ') || '-'} |`);
  }
  L.push('', '| Edge | Access | Mode | Gate | Length (blocks) | Waypoints |', '|---|---|---|---|---|---|');
  for (const e of EDGES) {
    const pts = edgePolyline(e, e.a);
    L.push(`| ${e.a} ↔ ${e.b} | ${e.access} | ${e.mode} | ${e.gate ?? '-'} | ${polylineLength(pts).toFixed(1)} | ${pts.length} |`);
  }
  L.push('', '## Command-block control room', '');
  L.push(`Underground at local y ${CONTROL.y} (world ${CONTROL.y + ORIGIN.y}), x ${CONTROL.x1}..${CONTROL.x2}, in ${CONTROL.rows.length} rows at local z ${CONTROL.rows.join(', ')}. Each of the ${MODULES.length} actuator modules is a redstone-block pad, an impulse block and its chain (east-facing). The full block-by-block register is docs/06_COMMAND_BLOCK_REGISTER.md.`, '');
  L.push(`## Inputs (${INPUTS.length})`, '');
  L.push('Every physical control sits on a console block; the impulse command block one block below it runs `scriptevent fb:input <action>`. The script accepts an input only if the event comes from the registered block position.', '');
  L.push('| ID | Action | Control | Control (local) | Command block (world) | Label |', '|---|---|---|---|---|---|');
  for (const i of INPUTS) {
    const [x, y, z] = inputCbPos(i);
    L.push(`| ${i.id} | \`${i.action}\` | ${i.kind} | ${i.p.join(' ')} | ${w(x, y, z)} | ${i.label} |`);
  }
  return L.join('\n') + '\n';
}

// ============================================================ 05 nights and balance
function powerMaths() {
  const P = CONFIG.power;
  const len = CONFIG.clock.ticksPerHour * CONFIG.clock.hours;
  const pc = (units) => (units / P.unitsPerPercent).toFixed(1);
  const L = [];
  L.push('## Power model', '');
  L.push(`Fixed-point integers: **${P.unitsPerPercent} units = 1 %**, start ${P.start} units (100 %). Every tick drains the base rate plus each active device. A night is ${len} ticks (${CONFIG.clock.hours} hours × ${CONFIG.clock.ticksPerHour}; 8 minutes at 20 TPS). Integer arithmetic makes results identical on every platform.`, '');
  L.push('| Consumer | Units / tick | % per second | % per in-game hour |', '|---|---|---|---|');
  const row = (name, u) => L.push(`| ${name} | ${u} | ${((u * 20) / P.unitsPerPercent).toFixed(2)} | ${pc(u * CONFIG.clock.ticksPerHour)} |`);
  row('Base drain, nights 0-1', P.baseDrain[1]);
  row('Base drain, nights 2-6', P.baseDrain[6]);
  row('Each closed door', P.door);
  row('Each lit hall light', P.light);
  row('Camera monitor up', P.cams);
  row('Office hatch sealed', P.hatch);
  L.push('', `One-shot costs: emergency strobe ${pc(P.strobeCost)} %, breaker reset ${pc(P.breakerResetCost)} %. Emergency reserve (nights 3+): one ${pc(P.reserveAmount)} % top-up if the lever is pulled within ${P.reserveWindow} ticks of reaching 0 %. Pre-shift power task: start at ${pc(P.start + P.taskBonus)} %.`, '');
  L.push('### Worked examples (full 9600-tick night)', '');
  L.push('| Night | Idle (base only) | Reasonable play* | Wasteful (everything on) |', '|---|---|---|---|');
  for (let n = 1; n <= 6; n++) {
    const base = P.baseDrain[n] * len;
    const hasHatch = n >= 4;
    const strobes = n >= 4 ? 2 : 0;
    const reasonable = base + 0.3 * len * P.cams + 2 * 0.08 * len * P.light + 2 * 0.1 * len * P.door + (hasHatch ? 0.05 * len * P.hatch : 0) + strobes * P.strobeCost;
    const perTick = P.baseDrain[n] + 2 * P.door + 2 * P.light + P.cams + (hasHatch ? P.hatch : 0);
    const zeroAt = Math.ceil(P.start / perTick);
    L.push(`| ${n} | ${pc(base)} % used → ${pc(P.start - base)} % left | ${pc(reasonable)} % used → ${pc(P.start - reasonable)} % left | ${perTick} units/tick: 0 % after ${zeroAt} ticks (${(zeroAt / CONFIG.clock.ticksPerHour).toFixed(2)} h, ${Math.round(zeroAt / 20)} s) |`);
  }
  L.push('', '\\* Reasonable: monitor up 30 % of the night, each hall light on 8 %, each door closed 10 %, hatch sealed 5 % (nights 4+), two strobe shots (nights 4+).', '');
  return L.join('\n');
}

async function nightsAndBalance() {
  const L = [];
  L.push('# 05 · Nights, formulas and balance', '', GEN, '');
  L.push('## Night table', '');
  L.push('Aggression (A) is 0-20. Activation = tick at which the character leaves home. Nights ≥ 2 add the hourly ramp ' + `[${CONFIG.hourlyRamp.join(', ')}] (12 AM..5 AM) to every character except Fredbear (cap 20).`, '');
  L.push('| Night | Title | Freddy | Bonnie | Chica | Fredbear | Activation F/B/C/G (ticks) | Strobe | Reserve | Max sabotage | Fredbear phase | Events |', '|---|---|---|---|---|---|---|---|---|---|---|---|');
  for (let n = 0; n <= 6; n++) {
    const d = CONFIG.nights[n];
    const ev = d.events.map((e) => `${e.kind}${e.task ? `:${e.task}` : e.id ? `:${e.id}` : ''}@${e.at}`).join(', ') || '-';
    const fb = d.fredbear.phase ? `${d.fredbear.phase} (entries ${d.fredbear.entries.join('/')}, max ${d.fredbear.maxAttempts} attempts, powers ${d.fredbear.powers.join(', ')})` : 'dormant';
    L.push(`| ${n} | ${d.title} | ${d.ai.freddy} | ${d.ai.bonnie} | ${d.ai.chica} | ${d.ai.fredbear} | ${d.activation.freddy}/${d.activation.bonnie}/${d.activation.chica}/${d.activation.fredbear} | ${d.strobeCharges} | ${d.reserve ? 'yes' : 'no'} | ${d.maxSabotage} | ${fb} | ${ev} |`);
  }
  L.push('', 'Night 0 is the training shift / vertical slice (400 ticks per hour; the tutorial further slows it to 12000 so the clock never ends a lesson).', '');
  L.push('## Formulas (ticks)', '');
  const C = CONFIG.characters;
  const f = [
    ['Bonnie telegraph (door corner) before attacking', C.bonnie.telegraph],
    ['Bonnie recovery after being repelled', C.bonnie.recover],
    ['Chica telegraph', C.chica.telegraph],
    ['Chica recovery', C.chica.recover],
    ['Freddy patience (right door open, monitor down)', C.freddy.patience],
    ['Freddy recovery', C.freddy.recover],
    ['Fredbear W1: music box — close that barrier', C.fredbear.w1],
    ['Fredbear W2: forcing — strobe now', C.fredbear.w2],
  ];
  L.push('| Window | Formula | A = 5 | A = 10 | A = 15 | A = 20 |', '|---|---|---|---|---|---|');
  for (const [name, fn] of f) L.push(`| ${name} | \`${fn.toString().replace(/\(a\) => /, '')}\` | ${fn(5)} | ${fn(10)} | ${fn(15)} | ${fn(20)} |`);
  L.push('', `Movement opportunities: Bonnie every ${C.bonnie.moInterval} ticks, Chica ${C.chica.moInterval}, Freddy ${C.freddy.moInterval}, Fredbear ${C.fredbear.moInterval}. At each opportunity a d20 roll ≤ A moves the character (bounded randomness; seeded mulberry32 so a seed replays exactly).`);
  L.push(`Fredbear W3 (barrier jammed open, strobe still works) = ${C.fredbear.w3} ticks; a strobe without a closed/jammed barrier only stuns him for ${C.fredbear.stunTicks} ticks. Freddy slips in after ${C.freddy.slipTicks} ticks of camera use with the right door open; Bonnie flanks from A ≥ ${C.bonnie.flankMinAI} and uses the vent from A ≥ ${C.bonnie.ventMinAI}; Chica sabotage chance per opportunity = A/40 (cooldown ${C.chica.sabotageCooldown}).`, '');
  L.push(`Director limits: at most ${CONFIG.director.maxConcurrentEntries} entries engaged at once, one attack token, nobody engages beside Fredbear, ${CONFIG.director.blackoutGrace}-tick grace after a blackout and ${CONFIG.director.maintenanceGrace} after maintenance. Adaptation memory is capped: door-use counters 0-10 per entry, noise heat 0-10 (decays every ${CONFIG.director.noiseDecayTicks} ticks), camera focus decays ×${CONFIG.director.camFocusDecay} per tick.`, '');
  L.push(powerMaths());
  L.push('## Simulation results', '');
  L.push('Produced by `node tools/balance_sim.mjs` (seeds 1000+; identical on every run). The oracle reads the true AI state and proves a valid defence exists every night; the human models react only to what a player can perceive (lights they switch on, the feed they watch, audio captions) with 8-20 tick reaction delays and imperfect routines. These are models, not playtests.', '');
  const res = await simulate();
  fs.writeFileSync(path.join(ROOT, 'tools/out/balance.json'), JSON.stringify(res, null, 1));
  L.push(table(res), '');
  for (const k of ['oracle', 'human', 'human_low']) L.push(`### ${res[k].label}`, '', detailTable(res, k), '');
  L.push('### Reading the results', '');
  L.push('* The oracle wins every seed of every night with power to spare (lowest point on night 6 shown above): no night is unwinnable.');
  L.push('* Idle play usually survives night 1 (the introduction), rarely night 2 and never from night 3; "everything on" always runs out of power — power management matters.');
  L.push('* The human models lose almost exclusively to **power exhaustion followed by Freddy\'s power-out sequence** from night 4 on, not to unfair attacks: every attack is preceded by its telegraph window. This is the intended pressure (Fredbear\'s hatch/strobe defence costs power) and also the first tuning knob if playtesting shows nights 5-6 are too hard: lower `power.door` / `power.hatch` or the night 5-6 base drain in `scripts/core/config.js`.');
  L.push('');
  return L.join('\n') + '\n';
}

if (import.meta.url === `file://${process.argv[1]}`) {
  fs.mkdirSync(path.join(ROOT, 'tools/out'), { recursive: true });
  fs.writeFileSync(path.join(ROOT, 'docs/02_FLOOR_PLAN.md'), floorPlan());
  fs.writeFileSync(path.join(ROOT, 'docs/05_NIGHTS_AND_BALANCE.md'), await nightsAndBalance());
  console.log('docs: 02_FLOOR_PLAN.md, 05_NIGHTS_AND_BALANCE.md written');
}
