// Generates the data-heavy documents straight from the source data so they
// can never drift from what the packs actually contain:
//   docs/02_FLOOR_PLAN.md          coordinate registry, rooms, cameras, route graph, inputs
//   docs/05_NIGHTS_AND_BALANCE.md  night table, formulas, power maths, simulation results
// Run: node tools/gen_docs.mjs   (re-runs the balance simulation, ~15 s)
import fs from 'node:fs';
import path from 'node:path';
import { ORIGIN, LEVELS, ROOMS, STAIRS, OPENINGS, TICKING_AREAS, ANCHORS, PROPERTY, OFFICE_BOUNDS } from '../packs/FredbearBP/scripts/data/layout.js';
import { NODES, EDGES, ACCESS, ENTRY_NODE, ENTRY_BARRIER, GOLDEN_NODES, edgePolyline, polylineLength } from '../packs/FredbearBP/scripts/data/nodes.js';
import { CAMERAS } from '../packs/FredbearBP/scripts/data/cameras.js';
import { INPUTS, inputCbPos } from '../packs/FredbearBP/scripts/data/inputs.js';
import { CONTROL, MODULES } from '../packs/FredbearBP/scripts/data/actuators.js';
import { CONFIG, nightDef } from '../packs/FredbearBP/scripts/core/config.js';
import { simulate, table, detailTable, simulateChallenges, challengeTable } from './balance_sim.mjs';
import { GuideGraph } from '../packs/FredbearBP/scripts/core/guide_path.js';
import { GUIDE_NODES, GUIDE_EDGES, GUIDE_TARGETS } from '../packs/FredbearBP/scripts/data/guide_graph.generated.js';
import { MAINTENANCE, TASKS } from '../packs/FredbearBP/scripts/data/story.js';
import { roomAt, ROOM_BY_ID } from '../packs/FredbearBP/scripts/data/layout.js';

const ROOT = new URL('../', import.meta.url).pathname;
const w = (x, y, z) => `${x + ORIGIN.x} ${y + ORIGIN.y} ${z + ORIGIN.z}`;
const fmt = (v) => (Number.isInteger(v) ? String(v) : v.toFixed(1));
const GEN = '<!-- GENERATED by tools/gen_docs.mjs from the pack data. Do not edit by hand. -->';

// ============================================================ 02 floor plan
function floorPlan() {
  const L = [];
  L.push('# 02 · Floor plan and coordinate registry', '', GEN, '');
  L.push('## Coordinate system', '');
  L.push(`All map data is authored in **local coordinates**. World = local + ORIGIN, with ORIGIN = (${ORIGIN.x}, ${ORIGIN.y}, ${ORIGIN.z}).`);
  L.push('X runs west→east, Z runs north→south (Minecraft convention), Y is up.');
  L.push(`The property spans local x ${PROPERTY.x1}..${PROPERTY.x2}, z ${PROPERTY.z1}..${PROPERTY.z2} (a ${PROPERTY.x2 - PROPERTY.x1 + 1} × ${PROPERTY.z2 - PROPERTY.z1 + 1} footprint) on a plinth from local y ${PROPERTY.bottomY} to ${PROPERTY.topY} with a ${PROPERTY.berm}-block earth berm; outdoor grade is local y ${PROPERTY.gradeY}.`, '');
  L.push('| Level | Name | Floor block y (local) | Standing y (local) | Standing y (world) |', '|---|---|---|---|---|');
  for (const lv of Object.values(LEVELS)) L.push(`| ${lv.id} | ${lv.name} | ${lv.floorY} | ${lv.stand} | ${lv.stand + ORIGIN.y} |`);
  L.push('', '![Basement](floorplan_L0.png)', '![Ground floor](floorplan_L1.png)', '![Upper floor](floorplan_L2.png)', '');
  L.push('Legend for the rendered plans: walls `#`, props `p`, glass `g`, floors `.`, grass `,`, roofs `r`; coloured overlays show room labels, AI nodes, route edges, cameras and inputs (tools/render_floorplans.py).', '');
  L.push('## Ticking areas (chunk loading)', '');
  L.push('| Name | From (world) | To (world) |', '|---|---|---|');
  for (const t of TICKING_AREAS) L.push(`| ${t.name} | ${t.from.join(' ')} | ${t.to.join(' ')} |`);
  L.push('', 'Four ticking areas of 8 × 8 chunks keep the whole property, the basement and the command-block control room loaded at all times (created by the builder; `functions/fb/tickingareas.mcfunction` re-creates them).', '');
  L.push('## Anchors', '');
  L.push('| Anchor | Local x y z | World x y z | Yaw |', '|---|---|---|---|');
  for (const [k, a] of Object.entries(ANCHORS)) L.push(`| ${k} | ${fmt(a.x)} ${fmt(a.y)} ${fmt(a.z)} | ${fmt(a.x + ORIGIN.x)} ${fmt(a.y + ORIGIN.y)} ${fmt(a.z + ORIGIN.z)} | ${a.yaw ?? '-'} |`);
  L.push('', `Office interior bounds (local): x ${OFFICE_BOUNDS.x1}..${OFFICE_BOUNDS.x2}, z ${OFFICE_BOUNDS.z1}..${OFFICE_BOUNDS.z2}, y ${OFFICE_BOUNDS.y1}..${OFFICE_BOUNDS.y2}.`, '');
  L.push(`## Rooms (${ROOMS.length})`, '');
  L.push('Box = outer wall box `[x1, z1, x2, z2]` in local coordinates (walls included).', '');
  L.push('| ID | Name | Level | Box (local) | World NW corner | Zone | Purpose |', '|---|---|---|---|---|---|---|');
  for (const r of ROOMS) {
    const lv = LEVELS[r.level];
    L.push(`| ${r.id} | ${r.name} | ${r.level} | ${r.box.join(', ')} | ${w(r.box[0], lv.stand, r.box[1])} | ${r.zone ?? '-'} | ${(r.purpose ?? '').replace(/\|/g, '/')} |`);
  }
  L.push('', `Openings: ${OPENINGS.length} doors, archways and windows. Stairs, ladders and the office hatch:`, '');
  L.push('| ID | Kind | Local position | Direction | From → to standing y |', '|---|---|---|---|---|');
  for (const s of STAIRS) L.push(`| ${s.id} | ${s.kind} | ${s.x} ${s.z} | ${s.dir ?? '-'} | ${s.fromStand ?? '-'} → ${s.toStand ?? '-'} |`);
  L.push('', '## Security cameras (16)', '');
  L.push('| ID | Label | Room | Position (local) | Looks at (local) | Sees nodes | Farthest point from office seat | Notes |', '|---|---|---|---|---|---|---|---|');
  const seat = ANCHORS.officeSeat;
  const nodeById = Object.fromEntries(NODES.map((n) => [n.id, n]));
  let worst = 0;
  for (const c of CAMERAS) {
    const notes = [c.audioOnly ? 'audio only' : '', c.lostSignalBefore ? `no signal before night ${c.lostSignalBefore}` : ''].filter(Boolean).join('; ') || '-';
    const pts = [c.loc, c.look, ...c.sees.map((id) => [nodeById[id].x, nodeById[id].y, nodeById[id].z])];
    const far = Math.max(...pts.map((p) => Math.hypot(p[0] - seat.x, p[2] - seat.z)));
    worst = Math.max(worst, far);
    L.push(`| ${c.id} | ${c.label} | ${c.room} | ${c.loc.map(fmt).join(' ')} | ${c.look.map(fmt).join(' ')} | ${c.sees.join(', ') || '-'} | ${far.toFixed(0)} blocks (${Math.ceil(far / 16)} chunks) | ${notes} |`);
  }
  L.push('', `**Rendering reach.** Camera views move the player's *view* (\`minecraft:free\` camera) but not the player, so what a feed can show is limited by what the client has loaded around the player in the office. The farthest point any feed must show is ${worst.toFixed(0)} blocks (${Math.ceil(worst / 16)} chunks) from the office seat. Ticking areas keep those chunks *simulated* (puppets keep being teleported and synced) but do not by themselves make them *render*; set the render distance to at least ${Math.ceil(worst / 16) + 2} chunks (docs/08_INSTALL_AND_PLAY.md). Whether distant feeds render correctly at lower settings has not been verified in-game.`);
  L.push('', '## AI route graph', '');
  L.push(`${NODES.length} nodes and ${EDGES.length} edges. Every edge is a polyline of waypoints the puppet follows; tools/validate_map.mjs samples every 0.5 blocks of every polyline against the voxel model (body + head cells must be passable), and the in-game self-test repeats the check against the built world.`);
  L.push(`Access letters: ${Object.entries(ACCESS).map(([k, v]) => `${v} = ${k}`).join(', ')}. Entries: ${Object.entries(ENTRY_NODE).map(([k, v]) => `${k} → ${v} (barrier ${ENTRY_BARRIER[k]})`).join(', ')}. Fredbear's golden nodes: ${GOLDEN_NODES.join(', ')}.`, '');
  const seenBy = {};
  for (const c of CAMERAS) for (const n of c.sees) (seenBy[n] ??= []).push(c.id);
  L.push('| Node | Room | Local x y z | Flags | Seen by |', '|---|---|---|---|---|');
  for (const n of NODES) {
    const flags = [n.home ? `home of ${n.home}` : '', n.golden ? 'golden' : '', n.dark ? 'dark' : '', n.entry ? `entry ${n.entry}` : '', n.kitchen ? 'kitchen' : '', n.crawl ? 'crawl' : '', n.zone ? `zone ${n.zone}` : ''].filter(Boolean).join(', ');
    L.push(`| ${n.id} | ${n.room} | ${fmt(n.x)} ${fmt(n.y)} ${fmt(n.z)} | ${flags} | ${(seenBy[n.id] ?? []).join(', ') || '-'} |`);
  }
  L.push('', '| Edge | Access | Mode | Gate | Length (blocks) | Waypoints |', '|---|---|---|---|---|---|');
  for (const e of EDGES) {
    const pts = edgePolyline(e, e.a);
    L.push(`| ${e.a} ↔ ${e.b} | ${e.access} | ${e.mode} | ${e.gate ?? '-'} | ${polylineLength(pts).toFixed(1)} | ${pts.length} |`);
  }
  L.push('', '## Player route guidance', '');
  L.push(`The green breadcrumb sparkles (introduction, optional tasks, maintenance) follow a walkable waypoint graph generated from the voxel model by \`tools/gen_guide.mjs\`: ${GUIDE_NODES.length / 4} nodes (a 6-block grid in every room, both sides of every doorway, every stairway and the ladder, every control) and ${GUIDE_EDGES.length / 3} edges, each a straight line a player can walk both ways under the map validator's rules (steps, drops, no squeezing past corners). The game runs Dijkstra from the target and lays sparkles along the next 14 blocks of the real route.`, '');
  L.push('| From | To | Walking distance | Rooms on the way |', '|---|---|---|---|');
  const guide = new GuideGraph();
  const officeSeat = { x: ANCHORS.officeSeat.x, y: ANCHORS.officeSeat.y, z: ANCHORS.officeSeat.z };
  const lobby = { x: ANCHORS.lobbySpawn.x, y: ANCHORS.lobbySpawn.y, z: ANCHORS.lobbySpawn.z };
  const inputFor = (action) => INPUTS.find((i) => i.action === action).id;
  const trips = [['Time clock', lobby, 'Security office', 'anchor:officeSeat'],
    ...Object.values(MAINTENANCE).map((m) => ['Security office', officeSeat, m.title, inputFor(m.action)]),
    ...Object.entries(TASKS).map(([n, t]) => ['Time clock', lobby, `Night ${n} task`, inputFor(t.action)])];
  for (const [fromName, from, toName, target] of trips) {
    const f = guide.field(target);
    let i = guide.entry(from, f);
    const dist = Math.round(f.dist[i]);
    const rooms = [];
    while (i >= 0) {
      const nd = guide.node(i);
      const r = roomAt(nd.x, nd.y, nd.z)?.id;
      if (r && rooms.at(-1) !== r) rooms.push(r);
      i = f.next[i];
    }
    L.push(`| ${fromName} | ${toName} | ${dist} blocks | ${rooms.map((r) => ROOM_BY_ID[r].name).join(' → ')} |`);
  }
  L.push('', '## Command-block control room', '');
  L.push(`Underground at local y ${CONTROL.y} (world ${CONTROL.y + ORIGIN.y}), x ${CONTROL.x1}..${CONTROL.x2}, in ${CONTROL.rows.length} rows at local z ${CONTROL.rows.join(', ')}. Each of the ${MODULES.length} actuator modules is a redstone-block pad, an impulse block and its chain (east-facing). The full block-by-block register is docs/06_COMMAND_BLOCK_REGISTER.md.`, '');
  L.push(`## Inputs (${INPUTS.length})`, '');
  L.push('Every physical control sits on a console block; the impulse command block one block below it runs `scriptevent fb:input <action>`. The script accepts an input only if the event comes from the registered block position.', '');
  L.push('| ID | Action | Control | Control (local) | Command block (world) | Label |', '|---|---|---|---|---|---|');
  for (const i of INPUTS) {
    const [x, y, z] = inputCbPos(i);
    L.push(`| ${i.id} | \`${i.action}\` | ${i.kind} | ${i.p.join(' ')} | ${w(x, y, z)} | ${i.label} |`);
  }
  return L.join('\n') + '\n';
}

// ============================================================ 05 nights and balance
function powerMaths() {
  const P = CONFIG.power;
  const len = CONFIG.clock.ticksPerHour * CONFIG.clock.hours;
  const pc = (units) => (units / P.unitsPerPercent).toFixed(1);
  const L = [];
  L.push('## Power model', '');
  L.push(`Fixed-point integers: **${P.unitsPerPercent} units = 1 %**, start ${P.start} units (100 %). Every tick drains the base rate plus each active device. A night is ${len} ticks (${CONFIG.clock.hours} hours × ${CONFIG.clock.ticksPerHour}; 8 minutes at 20 TPS). Integer arithmetic makes results identical on every platform.`, '');
  L.push('| Consumer | Units / tick | % per second | % per in-game hour |', '|---|---|---|---|');
  const row = (name, u) => L.push(`| ${name} | ${u} | ${((u * 20) / P.unitsPerPercent).toFixed(2)} | ${pc(u * CONFIG.clock.ticksPerHour)} |`);
  const groups = new Map();
  for (let n = 0; n <= 9; n++) groups.set(P.baseDrain[n], [...(groups.get(P.baseDrain[n]) ?? []), n]);
  for (const [u, ns] of groups) row(`Base drain, nights ${ns.join(', ')}`, u);
  row('Each closed door', P.door);
  row('Each lit hall light', P.light);
  row('Camera monitor up', P.cams);
  row('Office hatch sealed', P.hatch);
  L.push('', `One-shot costs: emergency strobe ${pc(P.strobeCost)} %, breaker reset ${pc(P.breakerResetCost)} %, vent / shaft seal ${pc(CONFIG.seals.cost)} % (sealed ${CONFIG.seals.duration} ticks, then ${CONFIG.seals.cooldown} ticks to recharge). Emergency reserve (nights 3+): one ${pc(P.reserveAmount)} % top-up if the lever is pulled within ${P.reserveWindow} ticks of reaching 0 %. Pre-shift power task: start at ${pc(P.start + P.taskBonus)} %.`, '');
  L.push('### Worked examples (full 9600-tick night)', '');
  L.push('| Night | Idle (base only) | Reasonable play* | Wasteful (everything on) |', '|---|---|---|---|');
  for (let n = 1; n <= 9; n++) {
    const base = P.baseDrain[n] * len;
    const hasHatch = n >= 4;
    const strobes = n >= 4 ? 2 : 0;
    const reasonable = base + 0.3 * len * P.cams + 2 * 0.08 * len * P.light + 2 * 0.1 * len * P.door + (hasHatch ? 0.05 * len * P.hatch : 0) + strobes * P.strobeCost;
    const perTick = P.baseDrain[n] + 2 * P.door + 2 * P.light + P.cams + (hasHatch ? P.hatch : 0);
    const zeroAt = Math.ceil(P.start / perTick);
    L.push(`| ${n} | ${pc(base)} % used → ${pc(P.start - base)} % left | ${pc(reasonable)} % used → ${pc(P.start - reasonable)} % left | ${perTick} units/tick: 0 % after ${zeroAt} ticks (${(zeroAt / CONFIG.clock.ticksPerHour).toFixed(2)} h, ${Math.round(zeroAt / 20)} s) |`);
  }
  L.push('', '\\* Reasonable: monitor up 30 % of the night, each hall light on 8 %, each door closed 10 %, hatch sealed 5 % (nights 4+), two strobe shots (nights 4+).', '');
  return L.join('\n');
}

async function nightsAndBalance() {
  const L = [];
  L.push('# 05 · Nights, formulas and balance', '', GEN, '');
  L.push('## Night table', '');
  L.push('Aggression (A) is 0-20. Activation = tick at which the character leaves home. Nights ≥ 2 add the hourly ramp ' + `[${CONFIG.hourlyRamp.join(', ')}] (12 AM..5 AM) to every character except Fredbear (cap 20).`, '');
  L.push('| Night | Title | Freddy | Bonnie | Chica | Fredbear | Morgrave | Valek | Activation F/B/C/G/M/V (ticks) | Strobe | Reserve | Max sabotage | Fredbear phase | Events |', '|---|---|---|---|---|---|---|---|---|---|---|---|---|---|');
  const rows = [];
  for (let n = 0; n <= 9; n++) {
    if (CONFIG.nights[n].variants) for (const [k, v] of Object.entries(CONFIG.nights[n].variants)) rows.push([`${n} (${k})`, nightDef(n, v)]);
    else rows.push([String(n), nightDef(n)]);
  }
  for (const [n, d] of rows) {
    const ev = d.events.map((e) => `${e.kind}${e.task ? `:${e.task}` : e.id ? `:${e.id}` : ''}@${e.at}`).join(', ') || '-';
    const fb = d.fredbear.phase ? `${d.fredbear.phase} (entries ${d.fredbear.entries.join('/')}, max ${d.fredbear.maxAttempts} attempts, powers ${d.fredbear.powers.join(', ')}${d.fredbear.omnipresent ? ', everywhere' : ''})` : 'dormant';
    const act = ['freddy', 'bonnie', 'chica', 'fredbear', 'morgrave', 'valek'].map((w) => (d.activation[w] ?? 99999) >= 99999 ? 'off' : d.activation[w]).join('/');
    L.push(`| ${n} | ${d.title} | ${d.ai.freddy} | ${d.ai.bonnie} | ${d.ai.chica} | ${d.ai.fredbear} | ${d.ai.morgrave ?? 0} | ${d.ai.valek ?? 0} | ${act} | ${d.strobeCharges} | ${d.reserve ? 'yes' : 'no'} | ${d.maxSabotage} | ${fb} | ${ev} |`);
  }
  L.push('', 'Night 0 is the training shift / vertical slice (400 ticks per hour; the tutorial further slows it to 12000 so the clock never ends a lesson). Night 7 unlocks after night 6: only Fredbear hunts, everywhere at once (the trio are switched off in Parts & Service). Night 8 unlocks after night 7 and depends on the last night 7 ending (seal: Morgrave; burn: Valek). Night 9 unlocks after night 8: Fredbear, Morgrave and Valek together, the trio switched off again.', '');
  L.push('## Challenge modes', '');
  L.push('Unlocked after night 6. Each is a full night on a base night with overrides and session modifiers (`CONFIG.challenges`, `NightSession` options.mods).', '');
  L.push('| Challenge | Base night | Aggression F/B/C/G | Strobe | Modifiers | What the player gets back |', '|---|---|---|---|---|---|');
  for (const c of Object.values(CONFIG.challenges)) {
    const d = CONFIG.nights[c.base];
    const ai = { ...d.ai, ...(c.overrides.ai ?? {}) };
    L.push(`| ${c.title} | ${c.base} | ${ai.freddy}/${ai.bonnie}/${ai.chica}/${ai.fredbear} | ${c.overrides.strobeCharges ?? d.strobeCharges} | ${Object.entries(c.mods).map(([k, v]) => `${k}=${v}`).join(', ') || '-'} | ${c.text} |`);
  }
  L.push('');
  L.push('## Fredbear: doors that hold', '');
  L.push(`When a forcing window (W2) ends and that door or the hatch has not held yet tonight (and it is not the Golden Hour), it holds: Fredbear bows for ${CONFIG.characters.fredbear.yieldTicks} ticks and vanishes to the diner, which counts as one of his attempts. Otherwise the barrier is jammed open and W3 follows. Strobe charges are his attempts + 2 on nights 4-6 (night 4: ${CONFIG.nights[4].strobeCharges} for ${CONFIG.nights[4].fredbear.maxAttempts}, night 5: ${CONFIG.nights[5].strobeCharges} for ${CONFIG.nights[5].fredbear.maxAttempts}, night 6: ${CONFIG.nights[6].strobeCharges} for ${CONFIG.nights[6].fredbear.maxAttempts} + ${CONFIG.nights[6].fredbear.finale.extraCharges} for ${CONFIG.nights[6].fredbear.finale.extraAttempts} at 5 AM); night 7: ${CONFIG.nights[7].strobeCharges} charges for ${CONFIG.nights[7].fredbear.maxAttempts} attempts and night 9: ${CONFIG.nights[9].strobeCharges} for ${CONFIG.nights[9].fredbear.maxAttempts}, with three entries that can each hold once.`, '');
  L.push('## Formulas (ticks)', '');
  const C = CONFIG.characters;
  const f = [
    ['Bonnie telegraph (door corner) before attacking', C.bonnie.telegraph],
    ['Bonnie recovery after being repelled', C.bonnie.recover],
    ['Chica telegraph', C.chica.telegraph],
    ['Chica recovery', C.chica.recover],
    ['Freddy patience (right door open, monitor down)', C.freddy.patience],
    ['Freddy recovery', C.freddy.recover],
    ['Fredbear W1: music box — close that barrier', C.fredbear.w1],
    ['Fredbear W2: forcing — strobe now', C.fredbear.w2],
    ['Morgrave telegraph (left door / hatch)', C.morgrave.telegraph],
    ['Morgrave recovery (back in the walls)', C.morgrave.recover],
    ['Valek corner window (minus 20 per anger, floor ' + C.valek.minWindow + ')', C.valek.telegraph],
    ['Valek recovery', C.valek.recover],
  ];
  L.push('| Window | Formula | A = 5 | A = 10 | A = 15 | A = 20 |', '|---|---|---|---|---|---|');
  for (const [name, fn] of f) L.push(`| ${name} | \`${fn.toString().replace(/\(a\) => /, '')}\` | ${fn(5)} | ${fn(10)} | ${fn(15)} | ${fn(20)} |`);
  L.push('', `Movement opportunities: Bonnie every ${C.bonnie.moInterval} ticks, Chica ${C.chica.moInterval}, Freddy ${C.freddy.moInterval}, Fredbear ${C.fredbear.moInterval}, Morgrave ${C.morgrave.moInterval}, Valek ${C.valek.moInterval}. At each opportunity a d20 roll ≤ A moves the character (bounded randomness; seeded mulberry32 so a seed replays exactly).`);
  L.push(`Fredbear W3 (barrier jammed open, strobe still works) = ${C.fredbear.w3} ticks; a strobe without a closed/jammed barrier only stuns him for ${C.fredbear.stunTicks} ticks. Freddy slips in after ${C.freddy.slipTicks} ticks of camera use with the right door open; Bonnie flanks from A ≥ ${C.bonnie.flankMinAI} and uses the vent from A ≥ ${C.bonnie.ventMinAI}; Chica sabotage chance per opportunity = \`${C.chica.sabotageChance.toString().replace(/\(a\) => /, '')}\` (cooldown ${C.chica.sabotageCooldown}).`, '');
  L.push(`1.3 behaviours: double trouble (from A ≥ ${C.bonnie.partnerMinAI}, Bonnie or Chica joins whoever holds the right door; a pair needs twice the repel time), Bonnie's teamwork (A ≥ ${C.bonnie.teamworkMinAI}, chance ${C.bonnie.teamworkChance}, cooldown ${C.bonnie.teamworkCooldown}: bangs on the left door while Chica sneaks to the right), Chica flanks left from A ≥ ${C.chica.flankMinAI}. Morgrave gives up after ${C.morgrave.sealGiveUp} ticks against a seal; his scratch at the entry is heard ${Math.round(C.morgrave.arrivalCueChance * 100)} % of the time. Valek mimics another animatronic on ${Math.round(C.valek.mimicChance * 100)} % of his steps and hums at the corner ${Math.round(C.valek.humChance * 100)} % of the time; lighting him sends him away for ${C.valek.vanishTicks} ticks but raises his anger (max 2).`, '');
  L.push(`Director limits: at most ${CONFIG.director.maxConcurrentEntries} entries engaged at once, one attack token, nobody engages beside Fredbear, ${CONFIG.director.blackoutGrace}-tick grace after a blackout and ${CONFIG.director.maintenanceGrace} after maintenance. Adaptation memory is capped: door-use counters 0-10 per entry, noise heat 0-10 (decays every ${CONFIG.director.noiseDecayTicks} ticks), camera focus decays ×${CONFIG.director.camFocusDecay} per tick.`, '');
  L.push(powerMaths());
  L.push('## Simulation results', '');
  L.push('Produced by `node tools/balance_sim.mjs` (seeds 1000+; identical on every run). The oracle reads the true AI state and proves a valid defence exists every night; the human models react only to what a player can perceive (lights they switch on, the feed they watch, audio captions) with 8-20 tick reaction delays and imperfect routines. These are models, not playtests.', '');
  const res = await simulate();
  const ch = await simulateChallenges();
  fs.writeFileSync(path.join(ROOT, 'tools/out/balance.json'), JSON.stringify({ nights: res, challenges: ch }, null, 1));
  L.push(table(res), '');
  for (const k of ['oracle', 'human', 'human_low']) L.push(`### ${res[k].label}`, '', detailTable(res, k), '');
  L.push('### Challenge modes', '', challengeTable(ch), '');
  L.push('The challenges were tuned until the human model wins most runs ("manageable" was the owner\'s brief): Double Power Drain was first built as "everything x2" and won 0-3 % of human-model runs; it now doubles the devices only, gives a 25 % reserve and runs at calmer aggression.', '');
  L.push('### Reading the results', '');
  L.push('* The oracle wins every seed of every night with power to spare (lowest point on night 6 shown above): no night is unwinnable.');
  L.push('* Idle play usually survives night 1 (the introduction), rarely night 2 and never from night 3; "everything on" always runs out of power — power management matters.');
  L.push('* The human models lose mostly to **power exhaustion followed by the power-out sequence** (Fredbear\'s from night 4) on nights 4-6, not to unfair attacks: every attack is preceded by its telegraph window. This is the intended pressure and also the first tuning knob if playtesting shows nights 5-6 are too hard: lower `power.door` / `power.hatch` or the night 5-6 base drain in `scripts/core/config.js`.');
  L.push('* 1.3 fixed the "stuck at the door" bug. Stuck animatronics had kept doors shut and drained power, so with the fix nights 5-6 became much easier for the human models (93 % / 77 %, against 57 % / 37 % in 1.2). Their base drain went from 4 to 5 units per tick to bring the curve back.');
  L.push('* Night 7 (Fredbear alone, everywhere) and nights 8-9 are lost mid-night rather than to power. Night 8 is about as hard as night 7 either way. The burn version (Valek) is harder for the models because his mimicry fools a player who trusts the captions. Night 9 is the hardest night by design ("creepy, eerie and hard" was the brief). A perfect-information player still wins every seed. First knobs: `nights[7|9].fredbear.cooldown` / `maxAttempts`, `characters.morgrave.arrivalCueChance` and `characters.valek.mimicChance`.');
  L.push('');
  return L.join('\n') + '\n';
}

if (import.meta.url === `file://${process.argv[1]}`) {
  fs.mkdirSync(path.join(ROOT, 'tools/out'), { recursive: true });
  fs.writeFileSync(path.join(ROOT, 'docs/02_FLOOR_PLAN.md'), floorPlan());
  fs.writeFileSync(path.join(ROOT, 'docs/05_NIGHTS_AND_BALANCE.md'), await nightsAndBalance());
  console.log('docs: 02_FLOOR_PLAN.md, 05_NIGHTS_AND_BALANCE.md written');
}
