// Writes docs/06_COMMAND_BLOCK_REGISTER.md and docs/command_blocks.csv from the
// generated register (run tools/gen_structures.mjs first).
import fs from 'node:fs';
import path from 'node:path';
import { allCommandBlocks, structureGroups } from './gen_structures.mjs';
import { SECTIONS, MODULES, REPEATERS, layoutModules } from '../packs/FredbearBP/scripts/data/actuators.js';
import { INPUTS } from '../packs/FredbearBP/scripts/data/inputs.js';
import { CB_STRUCTURES } from '../packs/FredbearBP/scripts/data/cb_structures.generated.js';

const ROOT = new URL('../', import.meta.url).pathname;
const blocks = allCommandBlocks();
const esc = (s) => String(s).replace(/\|/g, '\\|');

const counts = blocks.reduce((a, b) => ((a[b.type] = (a[b.type] ?? 0) + 1), a), {});
const bySection = blocks.reduce((a, b) => ((a[b.section] = (a[b.section] ?? 0) + 1), a), {});
const { modules } = layoutModules();

let md = `# Command-Block Register

Generated by \`tools/gen_structures.mjs\` + \`tools/gen_cb_register.mjs\` from
\`scripts/data/actuators.js\` and \`scripts/data/inputs.js\`. Every command below was
parsed against Mojang's official 1.26.50 command metadata by \`tools/validate_commands.mjs\`.

Coordinates are **world** coordinates (local + (0, -50, 0)).

## Totals

| | Count |
|---|---:|
| Command blocks | **${blocks.length}** |
| Impulse (needs redstone) | ${counts.impulse} |
| Chain (always active) | ${counts.chain} |
| Repeating (always active) | ${counts.repeating} |
| Actuator modules (control room) | ${MODULES.length} |
| Physical inputs (buttons / levers / plates) | ${INPUTS.length} |
| Structure files | ${structureGroups().size} |

Per section: ${Object.entries(bySection).map(([k, v]) => `${k === 'IN' ? 'Inputs' : `${k} ${SECTIONS[k]}`}: ${v}`).join(' · ')}

### Why ${blocks.length} and not 150-250

The brief suggested roughly 150-250 *useful* blocks. This design ends higher, without padding, for three reasons:

1. **One module per physical state change.** Each module is a short chain the director
   triggers for exactly one effect (for example *left door closes*, *power meter segment 7 goes dark*,
   *hour lamp 3 lights*). Nothing runs speculatively.
2. **No \`/execute\`.** Command blocks loaded from a structure keep the command version stamped in the
   file, so the project deliberately avoids \`execute\` and conditional chains. Branching lives in the script, so
   a choice between two outcomes is two small modules instead of one conditional chain.
3. **75 of the blocks are inputs**: one hidden impulse block under each physical button, lever or plate.

Continuously running logic is limited to **one** repeating block: a 100-tick heartbeat.
Everything else runs only when triggered (an event-driven design: no per-tick command-block work).

## How modules are wired

\`\`\`
 pad (air)  ->  [impulse, needs redstone]  ->  [chain] -> [chain] -> ...     (all facing east, +X)
   ^ script places minecraft:redstone_block here        first block clears the pad (setblock pad air)
\`\`\`

* The **script** (night director) decides *what* happens and triggers modules through the actuator bus
  (\`scripts/mc/actuator_bus.js\`): at most one pad write per module per 2 ticks, retried if the chunk is not loaded.
* **Inputs** run \`scriptevent fb:input <action>\`. The script accepts an input only when the event's
  \`sourceBlock\` is the registered command block for that action.
* \`TRIGGER:<module>\` in \`actuators.js\` becomes \`setblock <pad> redstone_block\` (one module triggering another).

## Installation

Command blocks are **not** placed with \`/setblock\` (Bedrock \`setblock\` cannot carry command-block NBT).
They are shipped preconfigured inside \`.mcstructure\` files in the behavior pack
(\`structures/fb/*.mcstructure\`, identifiers \`fb:<name>\`) and placed by the builder with the stable
\`world.structureManager.place()\` API, the same mechanism as \`/structure load\`. Each file stores the command,
mode, conditional flag, redstone mode and tick delay for every block; command-block \`Version\` is 42 and the
block-state version is 18161159, both copied from a structure exported by Bedrock itself
(\`tools/ref/reference_command_blocks.mcstructure\`; checked by \`tests/structures.test.mjs\`). If a structure ever fails to load, **docs/07_CONSTRUCTION.md** describes
how to rebuild any module by hand from this table.

## Structure files

Each file is placed with its minimum corner at the listed world position (\`world.structureManager.place\`, equivalent to
\`/structure load <id> <x> <y> <z>\`). Cells that hold no command block are structure void, so loading never overwrites
the surrounding build.

| Structure id | World origin (min corner) | Size x×y×z | Command blocks |
|---|---|---|---:|
${CB_STRUCTURES.map((st) => `| \`${st.id}\` | ${st.at.join(' ')} | ${st.size.join('×')} | ${st.blocks} |`).join('\n')}

## Control room layout

The control room is under the parking lot (local x 20-180, z 164-196, floor y -10; world floor y -60).
Rows run along +X at local z ${[...new Set(modules.map((m) => m.z))].join(', ')} (world y -59). A sign north of each impulse
block names its module; the west wall labels each row's sections. Developer buttons are on the row at local z 166.

## Module index

| Module | Section | Pad (world) | Blocks | Purpose |
|---|---|---|---:|---|
${modules.map((p) => `| \`${p.module.id}\` | ${p.module.section} | ${p.pad[0]} ${p.pad[1] - 50} ${p.pad[2]} | ${p.length - 1} | ${esc(p.module.purpose)} |`).join('\n')}
${REPEATERS.map((r) => `| \`${r.id}\` | ${r.section} | (none) | 1 | ${esc(r.purpose)} |`).join('\n')}

## Every command block

Type: I = impulse, C = chain, R = repeating. Mode: NR = needs redstone, AA = always active.
All blocks are unconditional. Facing: E = east (+X, the chain direction), U = up (inputs; direction irrelevant).

| ID | World x y z | Type | Mode | Delay | Facing | Command | Purpose / trigger |
|---|---|---|---|---:|---|---|---|
${blocks.map((b) => `| \`${b.id}\` | ${b.world.join(' ')} | ${b.type[0].toUpperCase()} | ${b.alwaysActive ? 'AA' : 'NR'} | ${b.delay} | ${b.facing === 'east' ? 'E' : 'U'} | \`${esc(b.command)}\` | ${esc(b.purpose)}; ${esc(b.trigger)} |`).join('\n')}
`;

fs.writeFileSync(path.join(ROOT, 'docs/06_COMMAND_BLOCK_REGISTER.md'), md);
const csv = ['id,world_x,world_y,world_z,type,mode,delay,facing,conditional,command,purpose,trigger']
  .concat(blocks.map((b) => [b.id, ...b.world, b.type, b.alwaysActive ? 'always_active' : 'needs_redstone', b.delay, b.facing, b.conditional, b.command, b.purpose, b.trigger]
    .map((v) => `"${String(v).replace(/"/g, '""')}"`).join(',')));
fs.writeFileSync(path.join(ROOT, 'docs/command_blocks.csv'), csv.join('\n') + '\n');
console.log(`wrote docs/06_COMMAND_BLOCK_REGISTER.md (${blocks.length} blocks) and docs/command_blocks.csv`);
